---
- name: Fedora
  hosts: localhost
  connection: local
  tasks:
    - name: Get the username of the runner
      become: false
      command: whoami
      changed_when: false
      register: whoami
    # Install all required packages and libraries first
    - name: Install and update packages
      become: true
      import_tasks: "playbooks/packages/install_base_packages.yml"
    - name: Install and update rpm fusion packages
      become: true
      import_tasks: "playbooks/packages/install_rpm_fusion_packages.yml"
    - name: Install and update flatpak packages
      become: true
      import_tasks: "playbooks/packages/install_flatpak_packages.yml"
    # Configure everything next
    - name: Configure gsettings
      import_tasks: "playbooks/configure_gsettings.yml"
    - name: Configure zsh
      become: true
      become_user: "{{ whoami.stdout }}"
      import_tasks: "playbooks/configure_zsh.yml"
