---
- name: Fedora
  hosts: localhost
  connection: local
  tasks:
    - name: Install and update packages
      become: true
      import_tasks: "playbooks/install_base_packages.yml"
    - name: Install and update rpm fusion packages
      become: true
      import_tasks: "playbooks/install_rpm_fusion_packages.yml"
    - name: Install and update flatpak packages
      become: true
      import_tasks: "playbooks/install_flatpak_packages.yml"
