- name: Update dnf packages
  dnf:
    name: "*"
    state: latest

- name: Install adw-gtk3-theme (rpm)
  dnf:
    name: adw-gtk3-theme
    state: latest

- name: Install gnome tweaks
  dnf:
    name: gnome-tweaks
    state: latest

- name: Install chromium browser
  dnf:
    name: chromium
    state: latest

- name: Import visual studio code repository keys
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install visual studio code repository
  yum_repository:
    name: Visual Studio Code
    description: Visual Studio Code Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install visual studio code
  dnf:
    name: code
    state: latest

- name: Enable lazygit copr
  community.general.copr:
    state: enabled
    host: copr.fedorainfracloud.org
    name: atim/lazygit

- name: Install lazygit
  dnf:
    name: lazygit
    state: latest

- name: Enable hyprland copr
  community.general.copr:
    state: enabled
    host: copr.fedorainfracloud.org
    name: solopasha/hyprland

- name: Install hyprland
  dnf:
    name: hyprland-git
    state: latest

- name: Install zsh
  dnf:
    name:
      - zsh
      - util-linux
    state: latest

- name: Enable starship copr
  community.general.copr:
    state: enabled
    host: copr.fedorainfracloud.org
    name: atim/starship

- name: Install starship
  dnf:
    name: starship
    state: latest

- name: Download nvm install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
    dest: /tmp/nvm_install.sh

- name: Install nvm
  shell: /tmp/nvm_install.sh
