- name: Copy wallpapers
  copy:
    src: dotfiles/Wallpapers
    dest: ~/Pictures

- name: Copy .config
  copy:
    src: dotfiles/.config
    dest: ~/

- name: Install Jetbrains Mono Nerdfont
  shell: |
    mkdir -p ~/.local/share/fonts
    cd ~/.local/share/fonts && curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFont-Regular.ttf
