- name: Install flatpak
  dnf:
    name: flatpak
    state: latest

- name: Install vesktop
  community.general.flatpak:
    name: dev.vencord.Vesktop
    state: present

- name: Install Discord Canary
  community.general.flatpak:
    name: com.discordapp.DiscordCanary
    remote: flathub-beta
    state: present