- name: Update dnf packages
  dnf:
    name: "*"
    state: latest

- name: Install chromium browser
  dnf:
    name: chromium
    state: latest

- name: Import visual studio code repository keys
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install visual studio code repository
  yum_repository:
    name: Visual Studio Code
    description: Visual Studio Code Repository
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install visual studio code
  dnf:
    name: code
    state: latest

- name: Enable lazygit copr
  community.general.copr:
    state: enabled
    host: copr.fedorainfracloud.org
    name: atim/lazygit

- name: Install lazygit
  dnf:
    name: lazygit
    state: latest
