- name: Update dnf packages
  dnf:
    name: "*"
    state: latest

- name: Install chromium browser
  dnf:
    name: chromium
    state: latest

- name: Import Visual Studio Code repository keys
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: latest

- name: Install Visual Studio Code RHEL repository
  shell: |
    sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install Visual Studio Code
  dnf:
    name: code
    state: latest

- name: Enable lazygit copr
  community.general.copr:
    state: enabled
    host: copr.fedorainfracloud.org
    name: atim/lazygit

- name: Install lazygit
  dnf:
    name: lazygit
    state: latest
