- name: Install flatpak
  dnf:
    name: flatpak
    state: latest

- name: Add flathub beta remote
  community.general.flatpak_remote:
    name: flathub-beta
    state: present
    flatpakrepo_url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo

- name: Install vesktop
  community.general.flatpak:
    name: dev.vencord.Vesktop
    state: present

- name: Install Discord Canary
  community.general.flatpak:
    name: com.discordapp.DiscordCanary
    remote: flathub-beta
    state: present
